
package br.com.itsimple.smartcities.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-27T19:58:27.487-03:00
 * Generated source version: 3.2.4
 *
 */
public final class ClienteService_ClienteServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.smartcities.itsimple.com.br/", "ClienteServiceImplService");

    private ClienteService_ClienteServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ClienteServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ClienteServiceImplService ss = new ClienteServiceImplService(wsdlURL, SERVICE_NAME);
        ClienteService port = ss.getClienteServiceImplPort();

        {
        System.out.println("Invoking cadastrar...");
        br.com.itsimple.smartcities.service.Cliente _cadastrar_arg0 = new br.com.itsimple.smartcities.service.Cliente();
        _cadastrar_arg0.setEmail("Email405224564");
        _cadastrar_arg0.setIdCliente(1905767860);
        _cadastrar_arg0.setNome("Nome_0020132363153");
        _cadastrar_arg0.setSobrenome("Sobrenome1115456089");
        try {
            port.cadastrar(_cadastrar_arg0);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking buscar...");
        int _buscar_arg0 = -463166143;
        br.com.itsimple.smartcities.service.Cliente _buscar__return = port.buscar(_buscar_arg0);
        System.out.println("buscar.result=" + _buscar__return);


        }

        System.exit(0);
    }

}
