package br.com.itsimple.smartcities.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-27T19:58:27.557-03:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "ClienteServiceImplService",
                  wsdlLocation = "http://localhost:8080/ws-jpa-provider/services/ClienteServiceImplPort?wsdl",
                  targetNamespace = "http://service.smartcities.itsimple.com.br/")
public class ClienteServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.smartcities.itsimple.com.br/", "ClienteServiceImplService");
    public final static QName ClienteServiceImplPort = new QName("http://service.smartcities.itsimple.com.br/", "ClienteServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ws-jpa-provider/services/ClienteServiceImplPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ClienteServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ws-jpa-provider/services/ClienteServiceImplPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ClienteServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ClienteServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClienteServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ClienteServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ClienteServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ClienteServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ClienteService
     */
    @WebEndpoint(name = "ClienteServiceImplPort")
    public ClienteService getClienteServiceImplPort() {
        return super.getPort(ClienteServiceImplPort, ClienteService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClienteService
     */
    @WebEndpoint(name = "ClienteServiceImplPort")
    public ClienteService getClienteServiceImplPort(WebServiceFeature... features) {
        return super.getPort(ClienteServiceImplPort, ClienteService.class, features);
    }

}
