
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package br.com.itsimple.smartcities.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-27T19:58:27.540-03:00
 * Generated source version: 3.2.4
 *
 */

@javax.jws.WebService(
                      serviceName = "ClienteServiceImplService",
                      portName = "ClienteServiceImplPort",
                      targetNamespace = "http://service.smartcities.itsimple.com.br/",
                      wsdlLocation = "http://localhost:8080/ws-jpa-provider/services/ClienteServiceImplPort?wsdl",
                      endpointInterface = "br.com.itsimple.smartcities.service.ClienteService")

public class ClienteServiceImplPortImpl implements ClienteService {

    private static final Logger LOG = Logger.getLogger(ClienteServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see br.com.itsimple.smartcities.service.ClienteService#cadastrar(br.com.itsimple.smartcities.service.Cliente arg0)*
     */
    public void cadastrar(br.com.itsimple.smartcities.service.Cliente arg0) throws Exception_Exception   {
        LOG.info("Executing operation cadastrar");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see br.com.itsimple.smartcities.service.ClienteService#buscar(int arg0)*
     */
    public br.com.itsimple.smartcities.service.Cliente buscar(int arg0) {
        LOG.info("Executing operation buscar");
        System.out.println(arg0);
        try {
            br.com.itsimple.smartcities.service.Cliente _return = new br.com.itsimple.smartcities.service.Cliente();
            _return.setEmail("Email488768139");
            _return.setIdCliente(-450694294);
            _return.setNome("Nome_00201381386612");
            _return.setSobrenome("Sobrenome1389177593");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
