package br.com.itsimple.smartcities.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-27T19:58:27.552-03:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://service.smartcities.itsimple.com.br/", name = "ClienteService")
@XmlSeeAlso({ObjectFactory.class})
public interface ClienteService {

    @WebMethod
    @RequestWrapper(localName = "cadastrar", targetNamespace = "http://service.smartcities.itsimple.com.br/", className = "br.com.itsimple.smartcities.service.Cadastrar")
    @ResponseWrapper(localName = "cadastrarResponse", targetNamespace = "http://service.smartcities.itsimple.com.br/", className = "br.com.itsimple.smartcities.service.CadastrarResponse")
    public void cadastrar(
        @WebParam(name = "arg0", targetNamespace = "")
        br.com.itsimple.smartcities.service.Cliente arg0
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "buscar", targetNamespace = "http://service.smartcities.itsimple.com.br/", className = "br.com.itsimple.smartcities.service.Buscar")
    @ResponseWrapper(localName = "buscarResponse", targetNamespace = "http://service.smartcities.itsimple.com.br/", className = "br.com.itsimple.smartcities.service.BuscarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public br.com.itsimple.smartcities.service.Cliente buscar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
