
package br.com.itsimple.smartcities.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-27T19:58:27.533-03:00
 * Generated source version: 3.2.4
 */

@WebFault(name = "Exception", targetNamespace = "http://service.smartcities.itsimple.com.br/")
public class Exception_Exception extends java.lang.Exception {

    private br.com.itsimple.smartcities.service.Exception exception;

    public Exception_Exception() {
        super();
    }

    public Exception_Exception(String message) {
        super(message);
    }

    public Exception_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, br.com.itsimple.smartcities.service.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, br.com.itsimple.smartcities.service.Exception exception, java.lang.Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public br.com.itsimple.smartcities.service.Exception getFaultInfo() {
        return this.exception;
    }
}
